[2025-09-19T14:45:02.859+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_main.check_new_files scheduled__2025-09-19T14:30:00+00:00 [queued]>
[2025-09-19T14:45:02.872+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_main.check_new_files scheduled__2025-09-19T14:30:00+00:00 [queued]>
[2025-09-19T14:45:02.873+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-19T14:45:02.897+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): check_new_files> on 2025-09-19 14:30:00+00:00
[2025-09-19T14:45:02.906+0000] {standard_task_runner.py:60} INFO - Started process 1290 to run task
[2025-09-19T14:45:02.911+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_main', 'check_new_files', 'scheduled__2025-09-19T14:30:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpc0q01bio']
[2025-09-19T14:45:02.916+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask check_new_files
[2025-09-19T14:45:02.995+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_main.check_new_files scheduled__2025-09-19T14:30:00+00:00 [running]> on host ed735ff6f76b
[2025-09-19T14:45:03.145+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_etl_main' AIRFLOW_CTX_TASK_ID='check_new_files' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T14:30:00+00:00'
[2025-09-19T14:45:03.297+0000] {log.py:232} WARNING - [2025-09-19 14:45:03,296] INFO - crypto_etl - Listing files from bucket crypto-data with prefix 'raw-data/'
[2025-09-19T14:45:03.296+0000] {extract.py:26} INFO - Listing files from bucket crypto-data with prefix 'raw-data/'
[2025-09-19T14:45:03.316+0000] {log.py:232} WARNING - [2025-09-19 14:45:03,315] INFO - crypto_etl - Found 2 CSV files
[2025-09-19T14:45:03.315+0000] {extract.py:30} INFO - Found 2 CSV files
[2025-09-19T14:45:03.325+0000] {log.py:232} WARNING - [2025-09-19 14:45:03,325] INFO - crypto_etl - Found 0 unprocessed files out of 2 total
[2025-09-19T14:45:03.325+0000] {file_processor.py:25} INFO - Found 0 unprocessed files out of 2 total
[2025-09-19T14:45:03.327+0000] {logging_mixin.py:188} INFO - No new files to process
[2025-09-19T14:45:03.328+0000] {python.py:201} INFO - Done. Returned value was: no_new_files
[2025-09-19T14:45:03.329+0000] {branch.py:35} INFO - Branch into no_new_files
[2025-09-19T14:45:03.330+0000] {skipmixin.py:178} INFO - Following branch no_new_files
[2025-09-19T14:45:03.356+0000] {skipmixin.py:244} INFO - Skipping tasks [('validate_files', -1)]
[2025-09-19T14:45:03.426+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_main, task_id=check_new_files, execution_date=20250919T143000, start_date=20250919T144502, end_date=20250919T144503
[2025-09-19T14:45:03.486+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T14:45:03.544+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
