[2025-09-19T15:15:20.607+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_main.handle_quality_failure scheduled__2025-09-19T15:00:00+00:00 [queued]>
[2025-09-19T15:15:20.621+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_main.handle_quality_failure scheduled__2025-09-19T15:00:00+00:00 [queued]>
[2025-09-19T15:15:20.622+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-19T15:15:20.646+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): handle_quality_failure> on 2025-09-19 15:00:00+00:00
[2025-09-19T15:15:20.654+0000] {standard_task_runner.py:60} INFO - Started process 1790 to run task
[2025-09-19T15:15:20.660+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_main', 'handle_quality_failure', 'scheduled__2025-09-19T15:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpif9qjfw5']
[2025-09-19T15:15:20.665+0000] {standard_task_runner.py:88} INFO - Job 116: Subtask handle_quality_failure
[2025-09-19T15:15:20.754+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_main.handle_quality_failure scheduled__2025-09-19T15:00:00+00:00 [running]> on host ed735ff6f76b
[2025-09-19T15:15:20.913+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_etl_main' AIRFLOW_CTX_TASK_ID='handle_quality_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T15:00:00+00:00'
[2025-09-19T15:15:20.962+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-19T15:15:20.963+0000] {logging_mixin.py:188} INFO - 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:00:00+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:15:20.964+0000] {python.py:201} INFO - Done. Returned value was: 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:00:00+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:15:21.007+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_main, task_id=handle_quality_failure, execution_date=20250919T150000, start_date=20250919T151520, end_date=20250919T151521
[2025-09-19T15:15:21.073+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T15:15:21.115+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
