[2025-09-19T14:34:41.090+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_main.validate_files manual__2025-09-19T14:34:33.052848+00:00 [queued]>
[2025-09-19T14:34:41.111+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_main.validate_files manual__2025-09-19T14:34:33.052848+00:00 [queued]>
[2025-09-19T14:34:41.112+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-19T14:34:41.135+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): validate_files> on 2025-09-19 14:34:33.052848+00:00
[2025-09-19T14:34:41.144+0000] {standard_task_runner.py:60} INFO - Started process 1133 to run task
[2025-09-19T14:34:41.150+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_main', 'validate_files', 'manual__2025-09-19T14:34:33.052848+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpsaq6wavu']
[2025-09-19T14:34:41.154+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask validate_files
[2025-09-19T14:34:41.232+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_main.validate_files manual__2025-09-19T14:34:33.052848+00:00 [running]> on host ed735ff6f76b
[2025-09-19T14:34:41.370+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_etl_main' AIRFLOW_CTX_TASK_ID='validate_files' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T14:34:33.052848+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T14:34:33.052848+00:00'
[2025-09-19T14:34:41.539+0000] {log.py:232} WARNING - [2025-09-19 14:34:41,538] INFO - crypto_etl - Marked raw-data/2025/09/19/14/crypto_data_20250919_14.csv as processing
[2025-09-19T14:34:41.538+0000] {file_processor.py:44} INFO - Marked raw-data/2025/09/19/14/crypto_data_20250919_14.csv as processing
[2025-09-19T14:34:41.542+0000] {log.py:232} WARNING - [2025-09-19 14:34:41,541] INFO - crypto_etl - Reading CSV raw-data/2025/09/19/14/crypto_data_20250919_14.csv from bucket crypto-data
[2025-09-19T14:34:41.541+0000] {extract.py:37} INFO - Reading CSV raw-data/2025/09/19/14/crypto_data_20250919_14.csv from bucket crypto-data
[2025-09-19T14:34:41.565+0000] {log.py:232} WARNING - [2025-09-19 14:34:41,564] INFO - crypto_etl - Read CSV raw-data/2025/09/19/14/crypto_data_20250919_14.csv with 6 rows
[2025-09-19T14:34:41.564+0000] {extract.py:44} INFO - Read CSV raw-data/2025/09/19/14/crypto_data_20250919_14.csv with 6 rows
[2025-09-19T14:34:41.567+0000] {logging_mixin.py:188} INFO - âœ“ Valid structure: raw-data/2025/09/19/14/crypto_data_20250919_14.csv (6 records)
[2025-09-19T14:34:41.605+0000] {python.py:201} INFO - Done. Returned value was: extract_data
[2025-09-19T14:34:41.606+0000] {branch.py:35} INFO - Branch into extract_data
[2025-09-19T14:34:41.608+0000] {skipmixin.py:178} INFO - Following branch extract_data
[2025-09-19T14:34:41.642+0000] {skipmixin.py:244} INFO - Skipping tasks [('handle_validation_failure', -1), ('partial_validation_success', -1)]
[2025-09-19T14:34:41.701+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_main, task_id=validate_files, execution_date=20250919T143433, start_date=20250919T143441, end_date=20250919T143441
[2025-09-19T14:34:41.765+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T14:34:41.819+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
