[2025-09-19T15:09:02.924+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_main.handle_quality_failure manual__2025-09-19T15:08:46.846243+00:00 [queued]>
[2025-09-19T15:09:02.942+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_main.handle_quality_failure manual__2025-09-19T15:08:46.846243+00:00 [queued]>
[2025-09-19T15:09:02.943+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-19T15:09:02.967+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): handle_quality_failure> on 2025-09-19 15:08:46.846243+00:00
[2025-09-19T15:09:02.977+0000] {standard_task_runner.py:60} INFO - Started process 1678 to run task
[2025-09-19T15:09:02.984+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_main', 'handle_quality_failure', 'manual__2025-09-19T15:08:46.846243+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpl2h1nriv']
[2025-09-19T15:09:02.989+0000] {standard_task_runner.py:88} INFO - Job 108: Subtask handle_quality_failure
[2025-09-19T15:09:03.072+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_main.handle_quality_failure manual__2025-09-19T15:08:46.846243+00:00 [running]> on host ed735ff6f76b
[2025-09-19T15:09:03.217+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_etl_main' AIRFLOW_CTX_TASK_ID='handle_quality_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T15:08:46.846243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T15:08:46.846243+00:00'
[2025-09-19T15:09:03.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-19T15:09:03.266+0000] {logging_mixin.py:188} INFO - 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:08:46.846243+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:09:03.266+0000] {python.py:201} INFO - Done. Returned value was: 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:08:46.846243+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:09:03.313+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_main, task_id=handle_quality_failure, execution_date=20250919T150846, start_date=20250919T150902, end_date=20250919T150903
[2025-09-19T15:09:03.357+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T15:09:03.395+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
